name = "sfp"
main = "src/worker/index.ts"
compatibility_date = "2024-12-01"

[assets]
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "sfp-leaderboard"
database_id = "38491120-68ea-47e2-98cf-2f7d4cde7c73"
